'use client'

import { ArrowRight, BarChart3, Check, CircleAlert, CircleCheck, FileImage, Leaf, Menu, Microscope, Search, Sparkles, Sprout, Upload, X } from 'lucide-react'
import Image from 'next/image'
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from 'react'
import { DISEASE_INFO, predictDisease } from '@/lib/predictionService'
import { en } from '@/locales/en'
import { te } from '@/locales/te'

const translations = { en, te }
type Language = keyof typeof translations
type Copy = typeof en
const diseaseNames = Object.keys(DISEASE_INFO)
const diseaseColors: Record<string, string> = { Healthy: 'bg-green-100 text-green-700', Tungro: 'bg-amber-100 text-amber-700', 'Rice Hispa': 'bg-orange-100 text-orange-700', 'Brown Spot': 'bg-amber-100 text-amber-800', 'Neck Blast': 'bg-red-100 text-red-700', 'Narrow Brown Spot': 'bg-yellow-100 text-yellow-700', 'Leaf Blast': 'bg-red-100 text-red-800', 'Sheath Blight': 'bg-orange-100 text-orange-800', 'Leaf Scald': 'bg-yellow-100 text-yellow-800', 'Bacterial Leaf Blight': 'bg-red-100 text-red-700' }

function Logo() {
  return <a href="#home" className="flex min-w-0 items-center gap-2 sm:gap-3" aria-label="Vari Raksha AI home"><Image src="/variraksha-logo.svg" alt="Variraksha logo" width={48} height={48} className="h-10 w-10 shrink-0 object-contain sm:h-12 sm:w-12" /><span className="min-w-0 leading-tight"><span className="block truncate text-base font-bold text-forest-green sm:text-lg">Vari Raksha AI</span><span className="block text-xs font-medium text-text-secondary">వరి రక్ష</span></span></a>
}

function LanguageSwitch({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) {
  return <div className="inline-flex items-center rounded-lg border border-border bg-bg p-1 text-sm" aria-label="Select language"><button onClick={() => setLanguage('en')} className={`rounded-md px-3 py-1.5 font-semibold ${language === 'en' ? 'bg-white text-forest-green shadow-sm' : 'text-text-secondary'}`}>English</button><button onClick={() => setLanguage('te')} className={`rounded-md px-3 py-1.5 font-semibold ${language === 'te' ? 'bg-white text-forest-green shadow-sm' : 'text-text-secondary'}`}>తెలుగు</button></div>
}

function Navbar({ t, language, setLanguage }: { t: Copy; language: Language; setLanguage: (language: Language) => void }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const links = [[t.nav.home, '#home'], [t.nav.library, '#library'], [t.nav.about, '#about']]
  return <header className="sticky top-0 z-40 border-b border-border/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-2 sm:px-5 sm:py-3 lg:px-8"><Logo /><nav className="hidden items-center gap-7 md:flex" aria-label="Main navigation">{links.map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-text-secondary hover:text-forest-green">{label}</a>)}</nav><div className="hidden items-center gap-4 md:flex"><LanguageSwitch language={language} setLanguage={setLanguage} /><a href="#home" className="btn-primary px-4 py-2.5 text-sm">{t.nav.action}</a></div><button className="focus-ring shrink-0 rounded-lg p-2 text-forest-green md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="border-t border-border bg-white px-4 pb-5 pt-2 md:hidden" aria-label="Mobile navigation"><div className="mb-2 py-3"><LanguageSwitch language={language} setLanguage={setLanguage} /></div>{links.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="block border-b border-border py-3 text-sm font-medium text-text-secondary">{label}</a>)}<a href="#home" onClick={() => setMenuOpen(false)} className="btn-primary mt-4 block text-center text-sm">{t.nav.action}</a></nav>}</header>
}

function Hero({ t }: { t: Copy }) {
  return <section id="home" className="overflow-hidden bg-cream"><div className="mx-auto grid max-w-7xl items-center gap-8 px-4 py-10 sm:px-5 sm:py-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-12 lg:px-8 lg:py-20"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-green-600/20 bg-green-50 px-3 py-1.5 text-sm font-semibold text-forest-green"><Sprout className="h-4 w-4" />{t.hero.eyebrow}</div><h1 className="max-w-xl text-4xl font-bold leading-tight tracking-tight text-text-primary sm:text-5xl lg:text-6xl">{t.hero.title}</h1><p className="mt-5 max-w-lg text-base leading-7 text-text-secondary sm:text-lg">{t.hero.description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="#detection" className="btn-primary inline-flex items-center justify-center gap-2">{t.hero.action}<ArrowRight className="h-4 w-4" /></a><a href="#library" className="btn-secondary inline-flex items-center justify-center gap-2">{t.hero.library}</a></div></div><div className="relative min-h-[280px] overflow-hidden rounded-2xl bg-forest-green shadow-xl sm:min-h-[360px] lg:min-h-[470px]"><Image src="/rice-field.png" alt={t.hero.imageAlt} fill className="object-cover" priority /><div className="absolute inset-0 bg-gradient-to-t from-forest-green/70 via-transparent to-transparent" /><div className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-3 sm:bottom-6 sm:left-6 sm:right-6"><div className="rounded-xl bg-white/95 p-3 shadow-lg sm:p-4"><div className="flex items-center gap-2 text-sm font-bold text-forest-green"><Sparkles className="h-4 w-4" /> AI</div><p className="mt-1 text-xs text-text-secondary">{t.hero.supported}</p></div><div className="rounded-xl bg-forest-green px-3 py-3 text-white shadow-lg"><p className="text-2xl font-bold">10</p><p className="text-xs text-green-100">{t.hero.supported}</p></div></div></div></div></section>
}

function UploadArea({ t, onFile }: { t: Copy; onFile: (file: File) => void }) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [dragging, setDragging] = useState(false)
  const [error, setError] = useState('')
  const validate = (file?: File) => { if (!file) return; if (!['image/jpeg', 'image/png'].includes(file.type)) return setError(t.upload.invalidType); if (file.size > 10 * 1024 * 1024) return setError(t.upload.tooLarge); setError(''); onFile(file) }
  const handleDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); validate(event.dataTransfer.files[0]) }
  return <div><div onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={handleDrop} className={`rounded-xl border-2 border-dashed p-5 text-center sm:p-10 ${dragging ? 'border-green-600 bg-green-50' : 'border-green-100 bg-green-50/40'}`}><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-600"><Upload className="h-6 w-6" /></span><h3 className="mt-4 text-lg font-bold leading-7 text-text-primary">{t.upload.title}</h3><p className="mt-2 text-xs text-text-secondary">{t.upload.drop}</p><div className="mt-5 flex flex-col justify-center gap-3 sm:flex-row"><button className="btn-primary inline-flex min-h-12 items-center justify-center gap-2" onClick={() => inputRef.current?.click()}><FileImage className="h-4 w-4" />{t.upload.choose}</button><button className="btn-secondary inline-flex min-h-12 items-center justify-center gap-2" onClick={() => inputRef.current?.click()}><Sprout className="h-4 w-4" />{t.upload.camera}</button></div><p className="mt-4 text-xs text-text-secondary">{t.upload.formats}</p><input ref={inputRef} type="file" accept="image/jpeg,image/png" capture="environment" className="hidden" onChange={(event: ChangeEvent<HTMLInputElement>) => validate(event.target.files?.[0])} /></div>{error && <p className="mt-3 flex items-center gap-2 text-sm font-medium text-error" role="alert"><CircleAlert className="h-4 w-4 shrink-0" />{error}</p>}</div>
}

function ResultMessage({ t, tone, title, description, help, onReset }: { t: Copy; tone: 'error' | 'warning'; title: string; description: string; help?: string; onReset: () => void }) {
  return <div className={`rounded-xl border p-5 sm:p-6 ${tone === 'error' ? 'border-red-200 bg-red-50' : 'border-amber-200 bg-amber-50'}`} role="alert"><div className="flex items-start gap-3"><CircleAlert className={`mt-0.5 h-6 w-6 shrink-0 ${tone === 'error' ? 'text-error' : 'text-warning'}`} /><div><h3 className="text-xl font-bold text-text-primary">{title}</h3><p className="mt-2 text-text-secondary">{description}</p>{help && <p className="mt-2 text-sm text-text-secondary">{help}</p>}<button onClick={onReset} className="btn-primary mt-5">{t.result.another}</button></div></div></div>
}

function ResultCard({ t, file, onReset }: { t: Copy; file: File; onReset: () => void }) {
  const [result, setResult] = useState<Awaited<ReturnType<typeof predictDisease>> | null>(null)
  const [loading, setLoading] = useState(false)
  const [preview, setPreview] = useState('')
  useEffect(() => { const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url) }, [file])
  const analyze = async () => { setLoading(true); setResult(null); await new Promise((resolve) => setTimeout(resolve, 800)); setResult(await predictDisease(file)); setLoading(false) }
  const info = result ? DISEASE_INFO[result.disease] : null
  return <div className="space-y-5"><div className="flex flex-col gap-5 rounded-xl border border-border bg-white p-4 sm:p-5 md:flex-row md:items-center"><div className="relative aspect-[4/3] w-full shrink-0 overflow-hidden rounded-lg bg-green-50 md:w-56 md:aspect-square">{preview && <Image src={preview} alt={t.upload.previewAlt} fill className="object-cover" unoptimized />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-text-primary">{file.name}</p><p className="mt-1 text-xs text-text-secondary">{(file.size / 1024 / 1024).toFixed(2)} MB · {t.upload.ready}</p></div><button onClick={onReset} className="focus-ring shrink-0 rounded-lg p-2 text-text-secondary hover:bg-green-50" aria-label={t.upload.remove}><X className="h-5 w-5" /></button></div>{!result && !loading && <button onClick={analyze} className="btn-primary mt-6 inline-flex items-center gap-2"><Sparkles className="h-4 w-4" />{t.upload.analyze}</button>}{loading && <div className="mt-6 flex items-center gap-3 text-forest-green" role="status"><span className="h-5 w-5 animate-spin rounded-full border-2 border-green-100 border-t-green-600" /><div><p className="font-semibold">{t.upload.analyzing}</p><p className="text-sm text-text-secondary">{t.upload.analyzingDescription}</p></div></div>}</div></div>{result && (result.isInvalid ? <ResultMessage t={t} tone="error" title={t.result.invalidTitle} description={t.result.invalidDescription} help={t.result.invalidHelp} onReset={onReset} /> : result.isLowConfidence ? <ResultMessage t={t} tone="warning" title={t.result.uncertainTitle} description={t.result.uncertainDescription} onReset={onReset} /> : info ? <div className="rounded-xl border border-green-200 bg-green-50 p-5 sm:p-6"><div className="flex items-start gap-3"><CircleCheck className="mt-0.5 h-6 w-6 shrink-0 text-success" /><div className="min-w-0"><p className="text-sm font-semibold text-green-700">{t.result.title}</p><h3 className="mt-2 text-2xl font-bold text-text-primary">{info.name}</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-white/75 p-3"><p className="text-xs text-text-secondary">{t.result.predicted}</p><p className="mt-1 font-semibold text-text-primary">{info.name}</p></div><div className="rounded-lg bg-white/75 p-3"><p className="text-xs text-text-secondary">{t.result.confidence}</p><p className="mt-1 font-semibold text-text-primary">{(result.confidence * 100).toFixed(1)}%</p></div></div><div className="mt-5 border-t border-green-200 pt-4"><h4 className="font-bold text-text-primary">{t.result.diseaseInfo}</h4><p className="mt-2 text-sm leading-6 text-text-secondary">{info.description}</p><p className="mt-3 text-sm text-text-secondary"><strong>{t.result.symptoms}:</strong> {info.symptoms.join(', ')}</p></div><button onClick={onReset} className="btn-primary mt-5">{t.result.another}</button></div></div></div> : null)}</div>
}

function Detection({ t }: { t: Copy }) {
  const [file, setFile] = useState<File | null>(null)
  return <section id="home" className="scroll-mt-20 bg-white px-4 py-8 sm:px-5 sm:py-12 lg:px-8"><div className="mx-auto max-w-5xl"><h1 className="max-w-3xl text-4xl font-bold leading-tight tracking-tight text-text-primary sm:text-5xl lg:text-6xl">{t.hero.title}</h1><div className="mt-7 rounded-2xl border border-border bg-bg p-3 shadow-sm sm:mt-9 sm:p-6 md:p-8">{file ? <ResultCard t={t} file={file} onReset={() => setFile(null)} /> : <UploadArea t={t} onFile={setFile} />}</div></div></section>
}

function Library({ t }: { t: Copy }) {
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<string | null>(null)
  const filtered = diseaseNames.filter((name) => name.toLowerCase().includes(query.toLowerCase()))
  const selectedInfo = selected ? DISEASE_INFO[selected] : null
  return <section id="library" className="bg-bg px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-green-600">{t.library.eyebrow}</p><h2 className="section-title mt-3">{t.library.title}</h2><p className="section-subtitle">{t.library.description}</p></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-3 h-5 w-5 text-text-secondary" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.library.search} className="focus-ring w-full rounded-lg border border-border bg-white py-3 pl-10 pr-4 text-sm" aria-label={t.library.search} /></div></div>{selectedInfo && <div className="mt-8 rounded-xl border border-green-100 bg-white p-5 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${diseaseColors[selectedInfo.name]}`}>{t.library.profile}</span><h3 className="mt-4 text-2xl font-bold text-text-primary sm:text-3xl">{selectedInfo.name}</h3><p className="mt-3 max-w-2xl leading-7 text-text-secondary">{selectedInfo.description}</p></div><button onClick={() => setSelected(null)} className="focus-ring rounded-lg p-2 text-text-secondary hover:bg-green-50" aria-label={t.library.close}><X /></button></div><div className="mt-7 grid gap-6 border-t border-border pt-6 md:grid-cols-3"><div><h4 className="font-bold text-text-primary">{t.result.symptoms}</h4><ul className="mt-3 space-y-2 text-sm text-text-secondary">{selectedInfo.symptoms.map((item) => <li key={item} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-green-600" />{item}</li>)}</ul></div><div><h4 className="font-bold text-text-primary">{t.result.impact}</h4><p className="mt-3 text-sm leading-6 text-text-secondary">{selectedInfo.impact}</p></div><div><h4 className="font-bold text-text-primary">{t.result.management}</h4><p className="mt-3 text-sm leading-6 text-text-secondary">{selectedInfo.recommendations}</p></div></div></div>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{filtered.map((name) => <article key={name} className="card-base flex flex-col p-5"><div className="flex h-24 items-center justify-center rounded-lg bg-green-50"><Leaf className="h-12 w-12 text-green-600/70" /></div><div className="mt-4 flex items-start justify-between gap-2"><h3 className="font-bold text-text-primary">{name}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold ${diseaseColors[name]}`}>{name === 'Healthy' ? t.library.healthy : t.library.disease}</span></div><button onClick={() => setSelected(name)} className="focus-ring mt-4 inline-flex items-center gap-2 self-start text-sm font-bold text-forest-green">{t.library.view}<ArrowRight className="h-4 w-4" /></button></article>)}</div></div></section>
}

function About({ t }: { t: Copy }) {
  return <section id="about" className="bg-white px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-green-600">{t.about.eyebrow}</p><h2 className="section-title mt-3">{t.about.title}</h2><p className="mt-5 text-lg leading-8 text-text-secondary">{t.about.description}</p><a href="#detection" className="btn-primary mt-7 inline-flex items-center gap-2">{t.about.action}<ArrowRight className="h-4 w-4" /></a></div><div className="rounded-2xl bg-forest-green p-5 text-white sm:p-8"><h3 className="text-2xl font-bold">{t.about.title}</h3><div className="mt-7 space-y-3">{t.about.flow.map((step, index) => <div key={step} className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-green-600 text-sm font-bold">{index + 1}</span><span className="font-medium">{step}</span></div>)}</div><div className="mt-8 border-t border-white/20 pt-5"><h4 className="font-bold">{t.about.why}</h4><p className="mt-2 text-sm leading-6 text-green-100">{t.about.whyText}</p></div></div></div></section>
}

function Footer({ t }: { t: Copy }) {
  return <footer className="bg-forest-green px-4 py-8 text-white sm:px-5 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-end"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-green-100">{t.footer}</p></div><nav className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-green-100" aria-label="Footer navigation"><a href="#home">{t.nav.home}</a><a href="#library">{t.nav.library}</a><a href="#about">{t.nav.about}</a></nav></div><div className="mx-auto mt-7 max-w-7xl border-t border-white/15 pt-5 text-xs text-green-100">© 2026 Vari Raksha AI. All rights reserved.</div></footer>
}

export default function Page() {
  const [language, setLanguage] = useState<Language>('en')
  const t = translations[language] as Copy
  useEffect(() => { document.documentElement.lang = language === 'te' ? 'te' : 'en' }, [language])
  const statIcons = [BarChart3, Sparkles, FileImage, CircleCheck]
  return <main><Navbar t={t} language={language} setLanguage={setLanguage} /><Detection t={t} /><section className="border-b border-border bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 px-4 py-4 sm:px-5 sm:py-6 md:grid-cols-4 lg:px-8">{t.stats.map((label, index) => { const Icon = statIcons[index]; return <div key={label} className="flex items-center gap-3 border-border px-2 py-3 first:pl-0 md:border-r md:px-4 md:last:border-0"><Icon className="h-5 w-5 shrink-0 text-green-600" /><div><p className="font-bold text-text-primary">{index === 0 ? '10' : index === 1 ? 'AI' : index === 2 ? 'Leaf' : 'Simple'}</p><p className="text-xs text-text-secondary">{label}</p></div></div> })}</div></section><section className="bg-bg px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-widest text-green-600">{t.how.eyebrow}</p><h2 className="section-title mt-3">{t.how.title}</h2><p className="section-subtitle">{t.how.description}</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{t.how.steps.map(([title, copy], index) => <div key={title} className="card-base p-5 sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100 font-bold text-forest-green">0{index + 1}</span><Microscope className="mt-6 h-7 w-7 text-green-600" /><h3 className="mt-4 text-lg font-bold text-text-primary">{title}</h3><p className="mt-2 leading-7 text-text-secondary">{copy}</p></div>)}</div></div></section><Library t={t} /><About t={t} /><Footer t={t} /></main>
}
