export const en = {
  languageName: 'English',
  nav: { home: 'Home', detection: 'Rice Crop Disease Detection', library: 'Disease Library', about: 'About', action: 'Detect Disease' },
  hero: { eyebrow: '', title: 'Rice Crop Disease Detection', description: '', action: 'Upload Rice Crop Image', library: 'Explore Disease Library', imageAlt: 'Healthy rice crop in a paddy field', supported: '10 supported classes' },
  stats: ['Supported classes', 'AI-powered', 'Image based', 'Farmer friendly'],
  how: { eyebrow: 'Simple by design', title: 'How Vari Raksha AI Works', description: 'Check a possible rice crop disease in three simple steps.', steps: [['Upload image', 'Take or choose a clear rice crop leaf photo.'], ['Analyze image', 'The model checks visible patterns in your image.'], ['View result', 'See the predicted disease and confidence.']] },
  upload: { title: 'Upload Clear Rice Crop Image', description: '', drop: 'Drag and drop your image here, or choose a file.', choose: 'Choose Image', camera: 'Take Photo', formats: 'JPG, JPEG, or PNG · Up to 10 MB', invalidType: 'Please upload a JPG, JPEG, or PNG image.', tooLarge: 'Image size must be below 10 MB.', previewAlt: 'Uploaded rice crop leaf preview', change: 'Change Image', remove: 'Remove Image', ready: 'Ready to analyze', analyze: 'Analyze Image', analyzing: 'Analyzing Rice Crop Image...', analyzingDescription: 'Please wait while the image is being checked.' },
  result: { title: 'Rice Crop Disease Detection Result', predicted: 'Predicted Disease', confidence: 'Confidence', invalidTitle: 'Crop Not Detected', invalidDescription: 'Please upload a clear rice crop image.', invalidHelp: 'For best results, upload a clear and well-lit image of a rice crop leaf.', uncertainTitle: 'Prediction Uncertain', uncertainDescription: 'Please upload a clearer rice crop image.', another: 'Analyze Another Image', diseaseInfo: 'Disease Information', symptoms: 'Common symptoms', impact: 'Crop impact', management: 'Management' },
  library: { eyebrow: 'Know your crop', title: 'Rice Crop Disease Library', description: 'Learn about the ten rice crop classes supported by Vari Raksha AI.', search: 'Search diseases', profile: 'Disease profile', view: 'View Details', healthy: 'Healthy', disease: 'Disease', close: 'Close details' },
  about: { eyebrow: 'Built for early action', title: 'Clear technology for healthier rice crops.', description: 'Vari Raksha AI helps farmers identify possible rice crop diseases from images and choose a clear next step for the field.', action: 'Try Rice Crop Disease Detection', flow: ['Image upload', 'Image processing', 'AI model', 'Disease prediction', 'Confidence score'], why: 'Why early detection matters', whyText: 'Noticing changes early gives farmers more time to monitor a crop and seek expert guidance.' },
  footer: 'AI-powered Rice Crop Disease Detection for farmers.',
} as const